version: "3.9"

networks:
  cardholder_pwa:
    driver: bridge

services:
  db:
    image: mysql:8.3
    # image: mariadb:11.3
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cardholder_db
      MYSQL_USER: cardholder_user
      MYSQL_PASSWORD: cardholder_pass
      MYSQL_ROOT_PASSWORD: root_pass
      # MARIADB_DATABASE: cardholder_db
      # MARIADB_USER: cardholder_user
      # MARIADB_PASSWORD: cardholder_pass
      # MARIADB_ROOT_PASSWORD: root_pass
    volumes:
      - $HOME/.cardholder_pwa/mysql_data:/var/lib/mysql
      # - $HOME/.cardholder_pwa/mariadb_data:/var/lib/mysql
    networks:
      - cardholder_pwa
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "cardholder_user", "-pcardholder_pass"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: quenary/cardholder_pwa:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: mysql+asyncmy://cardholder_user:cardholder_pass@db:3306/cardholder_db
    networks:
      - cardholder_pwa
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request; exit(0) if urllib.request.urlopen(\"http://localhost:8000/api/system/health\").getcode() == 200 else exit(1)'"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "80:80"
