version: '3.8'

services:
  app:
    image: quenary/cardholder_pwa:latest
    ports:
      - "80:80"
    volumes:
      - $HOME/.cardholder_pwa:/cardholder_pwa
    environment:
      - DB_URL=sqlite:////cardholder_pwa/cardholder_pwa.db
    restart: unless-stopped