name: Build and Push Docker Image on Version Tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: quenary/cardholder_pwa

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract version from Git tag
      id: extract_version
      run: |
        echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
        echo "version=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

    - name: Check if Docker tag already exists
      id: check_tag
      run: |
        STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
          https://hub.docker.com/v2/repositories/${{ env.IMAGE_NAME }}/tags/${{ env.VERSION }}/)
        echo "Status: $STATUS"
        if [ "$STATUS" = "200" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Stop if image already exists
      if: steps.check_tag.outputs.exists == 'true'
      run: |
        echo "Image tag ${{ env.VERSION }} already exists in Docker Hub. Aborting."
        exit 1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and tag Docker image
      run: |
        docker build \
          --build-arg VERSION=${{ env.VERSION }} \
          -t $IMAGE_NAME:${{ env.VERSION }} \
          -t $IMAGE_NAME:latest .

    - name: Push Docker image (${{ env.VERSION }})
      run: docker push $IMAGE_NAME:${{ env.VERSION }}

    - name: Push Docker image (latest)
      run: docker push $IMAGE_NAME:latest
