name: Run Tests

on:
  pull_request:
    branches: [main]

jobs:
  frontend-tests:
    name: Run Frontend Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install frontend dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci

  backend-tests:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        id: python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.13
          activate-environment: true

      - name: Install dependencies
        run: uv sync --locked
        shell: bash

      - name: Run pytest
        run: uv run pytest

      - name: Run lint
        if: always()
        run: uv run ruff check backend

      - name: Run typechecks
        if: always()
        run: uv run mypy backend